// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: betakeys.proto

package betakeys

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeygenNumber string `protobuf:"bytes,1,opt,name=keygenNumber,proto3" json:"keygenNumber,omitempty"`
}

func (x *KeyNotification) Reset() {
	*x = KeyNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_betakeys_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyNotification) ProtoMessage() {}

func (x *KeyNotification) ProtoReflect() protoreflect.Message {
	mi := &file_betakeys_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyNotification.ProtoReflect.Descriptor instead.
func (*KeyNotification) Descriptor() ([]byte, []int) {
	return file_betakeys_proto_rawDescGZIP(), []int{0}
}

func (x *KeyNotification) GetKeygenNumber() string {
	if x != nil {
		return x.KeygenNumber
	}
	return ""
}

var File_betakeys_proto protoreflect.FileDescriptor

var file_betakeys_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x62, 0x65, 0x74, 0x61, 0x6b, 0x65, 0x79, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x62, 0x65, 0x74, 0x61, 0x6b, 0x65, 0x79, 0x73, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x35, 0x0a, 0x0f, 0x4b, 0x65, 0x79, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x6b, 0x65,
	0x79, 0x67, 0x65, 0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x32, 0x5b,
	0x0a, 0x0d, 0x4b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x4a, 0x0a, 0x15, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x61,
	0x6c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x12, 0x19, 0x2e, 0x62, 0x65, 0x74, 0x61, 0x6b,
	0x65, 0x79, 0x73, 0x2e, 0x4b, 0x65, 0x79, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x0c, 0x5a, 0x0a, 0x2e,
	0x2f, 0x62, 0x65, 0x74, 0x61, 0x6b, 0x65, 0x79, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_betakeys_proto_rawDescOnce sync.Once
	file_betakeys_proto_rawDescData = file_betakeys_proto_rawDesc
)

func file_betakeys_proto_rawDescGZIP() []byte {
	file_betakeys_proto_rawDescOnce.Do(func() {
		file_betakeys_proto_rawDescData = protoimpl.X.CompressGZIP(file_betakeys_proto_rawDescData)
	})
	return file_betakeys_proto_rawDescData
}

var file_betakeys_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_betakeys_proto_goTypes = []interface{}{
	(*KeyNotification)(nil), // 0: betakeys.KeyNotification
	(*empty.Empty)(nil),     // 1: google.protobuf.Empty
}
var file_betakeys_proto_depIdxs = []int32{
	0, // 0: betakeys.KeygenService.NotifyRegionalServers:input_type -> betakeys.KeyNotification
	1, // 1: betakeys.KeygenService.NotifyRegionalServers:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_betakeys_proto_init() }
func file_betakeys_proto_init() {
	if File_betakeys_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_betakeys_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_betakeys_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_betakeys_proto_goTypes,
		DependencyIndexes: file_betakeys_proto_depIdxs,
		MessageInfos:      file_betakeys_proto_msgTypes,
	}.Build()
	File_betakeys_proto = out.File
	file_betakeys_proto_rawDesc = nil
	file_betakeys_proto_goTypes = nil
	file_betakeys_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// KeygenServiceClient is the client API for KeygenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KeygenServiceClient interface {
	NotifyRegionalServers(ctx context.Context, in *KeyNotification, opts ...grpc.CallOption) (*empty.Empty, error)
}

type keygenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeygenServiceClient(cc grpc.ClientConnInterface) KeygenServiceClient {
	return &keygenServiceClient{cc}
}

func (c *keygenServiceClient) NotifyRegionalServers(ctx context.Context, in *KeyNotification, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/betakeys.KeygenService/NotifyRegionalServers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeygenServiceServer is the server API for KeygenService service.
type KeygenServiceServer interface {
	NotifyRegionalServers(context.Context, *KeyNotification) (*empty.Empty, error)
}

// UnimplementedKeygenServiceServer can be embedded to have forward compatible implementations.
type UnimplementedKeygenServiceServer struct {
}

func (*UnimplementedKeygenServiceServer) NotifyRegionalServers(context.Context, *KeyNotification) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyRegionalServers not implemented")
}

func RegisterKeygenServiceServer(s *grpc.Server, srv KeygenServiceServer) {
	s.RegisterService(&_KeygenService_serviceDesc, srv)
}

func _KeygenService_NotifyRegionalServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyNotification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeygenServiceServer).NotifyRegionalServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betakeys.KeygenService/NotifyRegionalServers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeygenServiceServer).NotifyRegionalServers(ctx, req.(*KeyNotification))
	}
	return interceptor(ctx, in, info, handler)
}

var _KeygenService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "betakeys.KeygenService",
	HandlerType: (*KeygenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyRegionalServers",
			Handler:    _KeygenService_NotifyRegionalServers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "betakeys.proto",
}
